#include "quartz.h"
/**
 * quartz_supply_chain.h — Supply Chain Security
 *
 * Threat model:
 *   A reseller buys ESP32 boards in bulk, flashes custom firmware with
 *   KNOWN eFuse keys, repackages them as "Quartz Ready Miners," and
 *   sells to unsuspecting buyers. Reseller retains every key and can
 *   sign transactions on behalf of every buyer.
 *
 * Defense: Cryptographic freshness proof.
 *
 * The eFuse key MUST be generated on-chip at first boot using the
 * hardware RNG. The device produces a "birth certificate" that proves:
 *
 *   1. The key was generated by THIS chip's RNG (not injected)
 *   2. The key has never left the device (eFuse is physically unreadable)
 *   3. The device was NOT pre-flashed by a reseller
 *
 * == Birth Certificate Protocol ==
 *
 * FIRST BOOT:
 *   1. Device checks if eFuse BLOCK6 is still empty (all zeros)
 *   2. If empty: generate 32 random bytes from hardware RNG
 *   3. Burn key into eFuse BLOCK6 (one-way, irreversible)
 *   4. Generate Ed25519 keypair from RNG (separate from eFuse key)
 *   5. Create birth certificate:
 *      - chip_id (MAC address)
 *      - eFuse_key_commit_hash: SHA-256(eFuse_key || chip_id || "QUARTZ_GENESIS")
 *        (a hash, not the key — proves key was burned without revealing it)
 *      - device_pubkey (Ed25519, for block signing)
 *      - first_boot_timestamp (from RTC at power-on)
 *      - firmware_hash: SHA-256(running firmware binary)
 *      - birth_signature: Ed25519 sign(device_privkey, all above fields)
 *
 *   6. Certificate stored in NVS and displayed on screen
 *
 * BUYER VERIFICATION (at purchase time):
 *   1. Buyer powers on device
 *   2. Device shows birth certificate on display:
 *      - Chip ID: AA:BB:CC:DD:EE:FF
 *      - Key Hash: 7f3a... (first 8 chars)
 *      - Born: 2026-08-15 14:23:07
 *      - FW: a1b2c3d4...
 *   3. Buyer scans QR code or reads serial output
 *   4. Buyer's phone app checks:
 *      a. Is this chip_id already registered on the network?
 *         → YES = REJECT (used device or clone)
 *      b. Does firmware_hash match official release?
 *         → NO = REJECT (custom firmware = possible key theft)
 *      c. Is first_boot_timestamp reasonable?
 *         → If device claims birth date BEFORE official firmware release,
 *           it's running old/custom firmware
 *      d. Birth signature valid?
 *         → Verifies integrity of certificate itself
 *
 * ANTI-PRE-FLASH DETECTION:
 *   Reseller's attack requires burning eFuse BEFORE shipping to buyer.
 *   But the birth certificate includes firmware_hash. If reseller
 *   reflashes with official firmware after burning eFuse:
 *     - firmware_hash changes (different binary)
 *     - But birth certificate was signed with old firmware's key
 *     - New firmware can't re-create certificate (eFuse already burned,
 *       can't generate new keypair bound to same eFuse)
 *     - MISMATCH detected: "Device eFuse committed but certificate
 *       signature invalid. Possible tampering."
 *
 *   If reseller keeps custom firmware:
 *     - firmware_hash doesn't match official release
 *     - Phone app shows: "UNOFFICIAL FIRMWARE — do not use"
 *
 * RESELLER CERTIFICATION PROGRAM:
 *   Authorized resellers receive a batch certificate:
 *     - Batch ID, reseller pubkey, device count, factory firmware hash
 *     - Signed by Quartz multi-sig (3-of-5)
 *   Buyers can verify their device came from an authorized batch.
 *   Unauthorized resellers still work but phone app warns:
 *   "Device not from authorized reseller — verify birth certificate carefully."
 */

#ifndef QUARTZ_SUPPLY_CHAIN_H
#define QUARTZ_SUPPLY_CHAIN_H

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

/* ============ Constants ============ */

#define QZ_CERT_VERSION         1
#define QZ_CHIP_ID_SIZE         6       /* MAC address */
#define QZ_PUBKEY_SIZE          32      /* Ed25519 public key */
#define QZ_SIG_SIZE             64      /* Ed25519 signature */
#define QZ_HASH_SIZE            32      /* SHA-256 */
#define QZ_TIMESTAMP_SIZE       8       /* uint64_t Unix timestamp */
#define QZ_FIRMWARE_HASH_SIZE   32      /* SHA-256 of running binary */

/* Birth certificate serialized size:
 * version(1) + chip_id(6) + key_commit_hash(32) + device_pubkey(32) +
 * timestamp(8) + firmware_hash(32) + reserved(3) + signature(64) = 178 bytes
 */
#define QZ_CERT_SIZE            178

/* ============ Data Structures ============ */

typedef struct {
    uint8_t  version;                           /* Certificate format version */
    uint8_t  chip_id[QZ_CHIP_ID_SIZE];          /* ESP32 MAC address */
    uint8_t  key_commit_hash[QZ_HASH_SIZE];     /* SHA-256(efuse_key || chip_id || "QUARTZ_GENESIS") */
    uint8_t  device_pubkey[QZ_PUBKEY_SIZE];     /* Ed25519 public key for block signing */
    uint64_t first_boot_timestamp;              /* When eFuse was first burned */
    uint8_t  firmware_hash[QZ_FIRMWARE_HASH_SIZE]; /* SHA-256 of firmware binary */
    uint8_t  reserved[3];                       /* Future use, zeros */
    uint8_t  birth_signature[QZ_SIG_SIZE];      /* Ed25519 signature over all above */
} qz_birth_certificate_t;

//_Static_assert(sizeof(qz_birth_certificate_t) == QZ_CERT_SIZE,

/* Verification result */
typedef enum {
    QZ_CERT_OK = 0,                 /* Certificate valid and fresh */
    QZ_CERT_ALREADY_REGISTERED = 1, /* Chip ID seen on network (clone?) */
    QZ_CERT_FIRMWARE_MISMATCH = 2,  /* Firmware hash ≠ official release */
    QZ_CERT_BAD_SIGNATURE = 3,      /* Certificate signature invalid */
    QZ_CERT_EFUSE_TAMPERED = 4,     /* eFuse burned but certificate invalid */
    QZ_CERT_EXPIRED = 5,            /* Certificate too old (pre-release date) */
    QZ_CERT_UNAUTHORIZED_RESELLER = 6, /* Not from authorized batch */
} qz_cert_status_t;

/* ============ API ============ */

/**
 * Initialize supply chain subsystem.
 * Called on every boot. Determines if this is first boot or subsequent.
 *
 * On first boot:
 *   - Generates and burns eFuse key
 *   - Creates birth certificate
 *   - Stores certificate in NVS
 *
 * On subsequent boots:
 *   - Loads existing certificate from NVS
 *   - Verifies firmware hash matches certificate
 *
 * @param cert_out  Output: loaded/created birth certificate
 * @return QZ_OK on success
 */
qz_err_t quartz_supply_chain_init(qz_birth_certificate_t *cert_out);

/**
 * Check if eFuse has been provisioned (key burned).
 * @return true if eFuse BLOCK6 is non-zero (key exists)
 */
bool quartz_efuse_is_provisioned(void);

/**
 * Generate and burn eFuse key on first boot.
 * Uses hardware RNG — key has never existed before this call.
 *
 * @param key_out  Output: the generated key (32 bytes)
 *                 WARNING: caller must zero this buffer after use
 * @return QZ_OK on success, QZ_ERR_INVALID if eFuse already provisioned
 */
qz_err_t quartz_efuse_provision(uint8_t key_out[32]);

/**
 * Create a birth certificate after eFuse provisioning.
 *
 * Steps:
 *   1. Compute key_commit_hash = SHA-256(eFuse_key || chip_id || "QUARTZ_GENESIS")
 *   2. Generate Ed25519 keypair from hardware RNG
 *   3. Hash running firmware binary
 *   4. Sign certificate fields with Ed25519 private key
 *   5. Destroy private key (only public key retained)
 *
 * @param cert  Output: signed birth certificate
 * @return QZ_OK on success
 */
qz_err_t quartz_create_birth_certificate(qz_birth_certificate_t *cert);

/**
 * Verify a birth certificate (used by phone app / network).
 *
 * @param cert              Certificate to verify
 * @param official_fw_hash   Expected firmware hash for this release
 * @param min_birth_date     Earliest acceptable birth timestamp (release date)
 * @param known_chip_ids     Set of chip IDs already on network (NULL = skip check)
 * @param known_count        Number of known chip IDs
 * @return QZ_CERT_OK if valid
 */
qz_cert_status_t quartz_verify_certificate(
    const qz_birth_certificate_t *cert,
    const uint8_t official_fw_hash[QZ_FIRMWARE_HASH_SIZE],
    uint64_t min_birth_date,
    const uint8_t (*known_chip_ids)[QZ_CHIP_ID_SIZE],
    size_t known_count
);

/**
 * Serialize certificate for QR code / serial output.
 * Format: hex string of QZ_CERT_SIZE bytes (356 chars + null).
 *
 * @param cert    Certificate to serialize
 * @param output  Buffer (must be at least 357 bytes)
 */
void quartz_cert_to_hex(const qz_birth_certificate_t *cert, char *output);

/**
 * Deserialize certificate from hex string.
 */
qz_err_t quartz_cert_from_hex(const char *hex, qz_birth_certificate_t *cert);

/**
 * Get short display hash for screen (first 4 bytes of key_commit_hash as hex).
 * Returns 8-char string like "7f3a9c01".
 */
void quartz_cert_short_hash(const qz_birth_certificate_t *cert, char out[9]);

/**
 * Check firmware integrity at runtime.
 * Hashes the running firmware and compares to certificate.
 *
 * @param cert  Birth certificate with expected firmware hash
 * @return true if firmware matches certificate
 */
bool quartz_verify_firmware_integrity(const qz_birth_certificate_t *cert);

/**
 * Detect tampering: eFuse burned but certificate missing or invalid.
 * This happens when a reseller burns eFuse with custom firmware,
 * then reflashes with official firmware.
 *
 * @return true if tampering detected (eFuse burned but no valid cert)
 */
bool quartz_detect_tampering(void);

#endif /* QUARTZ_SUPPLY_CHAIN_H */
